---
- hosts: 192.168.56.104
  become: true
  tasks:

  - name: install apache2 and php
    yum:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
